<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace local_oerexchange\local\sandbox;

/**
 * Moodle Playground sandbox integration (DESIGN.md §4, option B): branch
 * mapper + blueprint builder + launch-URL builder. Pure functions — no HTTP
 * calls, no orchestrator, no server-side trial execution. Replaces the
 * Podman-fleet client.php from DESIGN.md §3.
 *
 * @package    local_oerexchange
 * @copyright  2026 Adam Jenkins <adam@wisecat.net>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class playground {
    /**
     * Moodle versions the oer-sandbox deployment kit has actually built and
     * deployed, oldest first. Keep in sync with the kit's build list
     * (dev-docs/oer-platform/SANDBOX-UPGRADES.md).
     *
     * @var string[]
     */
    const DEPLOYED_BRANCHES = ['5.0', '5.2'];

    /**
     * Signed-download link TTL, seconds.
     */
    const SIGNED_URL_TTL = 900;

    /**
     * Plugins already baked into a deployed branch's bundle at build time
     * (installed into the snapshot's baseline database by Moodle's own
     * native admin/cli/install_database.php during the bundle build, NOT
     * by the WASM runtime's installMoodlePlugin step).
     *
     * Why this exists: found live, 2026-07-19 - the runtime installMoodlePlugin
     * step runs upgrade_noncore() *inside* the booted WASM PHP instance, and
     * a raw fatal there escapes the JS orchestration's own try/catch (Moodle's
     * default_exception_handler calls exit(1) first - see
     * reference-clones/moodle-playground/src/blueprint/steps/moodle-plugins.js
     * runMoodleUpgrade()), leaving the plugin's files present but its DB
     * registration incomplete. The bundle's baseline snapshot, by contrast,
     * is generated by oer-sandbox's build pipeline running Moodle's real CLI
     * installer on ordinary (non-WASM) PHP - the exact same reliable path
     * that installs the ~400 core tables every trial already boots with in
     * ~10 seconds. A plugin present in the Moodle source tree BEFORE that
     * snapshot is generated goes through that same reliable path instead of
     * the fragile runtime one. See
     * dev-docs/oer-platform/discoveries/2026-07-19-sandbox-thirdparty-plugin-db-install-limitation.md
     * for the full trace, and oer-sandbox's build docs for how a bundle here
     * is actually rebuilt with a plugin baked in.
     *
     * Keyed by deployed branch (matching DEPLOYED_BRANCHES); each value is a
     * list of 'type_name' frankenstyle components already present in that
     * branch's currently-deployed bundle. Keep in sync with what oer-sandbox
     * has actually built and deployed - this is a manual registry, not
     * derived from the allowlist (being on the plugin allowlist means "may
     * be requested for a trial", not "is baked into the bundle").
     *
     * @var array<string, string[]>
     */
    const BAKED_IN_PLUGINS = [
        // Verified working 2026-07-19, three independent ways, not just one:
        // (1) the rebuilt '5.2' bundle's install.sq3 snapshot has all 5
        // mdl_quizquest* tables and a config_plugins version row (direct
        // sqlite3 inspection); (2) a fresh boot's own admin/plugins.php
        // shows "Quiz Quest / mod_quizquest / 0.6.1 / Enabled" with an
        // Uninstall action available - a real, complete install, not a
        // partial "Additional / To be installed" one; (3) a full live
        // Try-it round trip on a WHOLE-COURSE resource requiring
        // mod_quizquest actually completes - the restored course renders
        // with its quiz and both Quiz Quest activities all present and
        // clickable (screenshots: mitigation1-course19-t24s.png).
        //
        // Caveat, found in the same verification pass: a SINGLE-ACTIVITY
        // mod_quizquest share (as opposed to a whole-course share) still
        // fails inside the sandbox with "Can't find data record in
        // database" - this is NOT a plugin-install problem (the plugin is
        // confirmed fully installed either way) but the sandbox-specific
        // manifestation of the already-documented, separate limitation that
        // a single quizquest activity's question-category reference can't
        // relocate into a course it never shared context with (see
        // WALKTHROUGH.md Part 4 / dev-docs/oer-platform/discoveries/
        // 2026-07-19-single-activity-quizquest-restore-in-wasm-sandbox.md).
        // On a real (non-WASM) site this degrades gracefully (the category
        // reference is simply cleared); in this WASM+SQLite environment it
        // throws instead. Practical guidance is unchanged from before this
        // fix: share the WHOLE COURSE if you want a Quiz Quest activity's
        // questions - and now its Try it - to work cleanly.
        '5.2' => ['mod_quizquest'],
    ];

    /**
     * Whether a plugin is already baked into a branch's deployed bundle, so
     * the runtime installMoodlePlugin step for it should be skipped entirely
     * (nothing to install - it's already there and fully registered).
     *
     * @param string $type
     * @param string $name
     * @param string $branch
     * @return bool
     */
    public static function is_baked_in(string $type, string $name, string $branch): bool {
        $component = $type . '_' . $name;
        return in_array($component, self::BAKED_IN_PLUGINS[$branch] ?? [], true);
    }

    /**
     * Map a resource's source Moodle version to the lowest deployed playground
     * branch that is >= it (restore is forward-compatible, never backward).
     * Falls back to the highest deployed branch if the source is newer than
     * everything we've deployed.
     *
     * @param string $sourceversion e.g. "4.5.2 (Build: 20250101)" or "5.2.1+"
     * @return string e.g. "5.2"
     */
    public static function map_branch(string $sourceversion): string {
        $deployed = self::DEPLOYED_BRANCHES;
        $newest = end($deployed);

        if (!preg_match('/(\d+)\.(\d+)/', $sourceversion, $matches)) {
            // Unparseable — assume it needs the newest deployed branch.
            return $newest;
        }
        $sourcenum = ((int) $matches[1]) * 100 + (int) $matches[2];

        foreach ($deployed as $branch) {
            [$maj, $min] = explode('.', $branch);
            $branchnum = ((int) $maj) * 100 + (int) $min;
            if ($branchnum >= $sourcenum) {
                return $branch;
            }
        }

        return $newest;
    }

    /**
     * Build the blueprint JSON for a trial: install, login, allowlisted
     * required plugins, restore the resource, land on the restored course.
     *
     * @param string $resourcetitle
     * @param string $signedmbzurl signed, short-lived, same-origin-reachable URL to the .mbz
     * @param array $allowedplugininstalls list of ['type'=>, 'name'=>, 'zipurl'=>] — already
     *                                     intersected with the pluginallowlist by the caller;
     *                                     this method does not consult resource metadata for
     *                                     what to install, only what it is given.
     * @param string $branch the deployed branch this trial will boot (e.g. "5.2") — used only
     *                        to skip a runtime install step for a plugin already baked into
     *                        that branch's bundle. Pass '' (default) to always emit runtime
     *                        install steps, e.g. from a caller that hasn't resolved a branch.
     * @param string $resourcetype 'course' or 'activity' (resources.type — a 'data' resource is
     *                              never Try-it-able and must not reach this method at all; see
     *                              its caller's guard). Defaults to 'course' so any caller not
     *                              yet updated keeps today's exact restoreCourse behavior.
     * @param string $language Moodle language code the trial should come up in — normally the
     *                          launching user's own current_language(). '' or 'en' emits no
     *                          language step at all (core ships English; every other language
     *                          is a downloaded pack). An unrecognisable code is dropped.
     * @return array the blueprint structure (JSON-encode before use)
     */
    public static function build_blueprint(
        string $resourcetitle,
        string $signedmbzurl,
        array $allowedplugininstalls,
        string $branch = '',
        string $resourcetype = 'course',
        string $language = ''
    ): array {
        $steps = [];

        $steps[] = [
            'step' => 'installMoodle',
            'options' => ['siteName' => $resourcetitle],
        ];
        if (self::is_installable_language($language)) {
            // A trial boots with core's English strings only; every other
            // language lives in a pack that Moodle's own lang_installer
            // downloads from download.moodle.org/langpack. Upstream's step
            // handler treats a failed download as non-fatal (it catches and
            // continues in English), so this can never cost the user their
            // trial - see reference-clones/moodle-playground/src/blueprint/
            // steps/moodle-language.js.
            //
            // setDefault is not optional in practice: the bundle's baseline
            // snapshot bakes admin.lang='en', and a logged-in user's own lang
            // overrides $CFG->lang, so without it the auto-logged-in admin
            // reads English out of a pack that installed perfectly. Upstream's
            // helper repoints pre-existing accounts for exactly this reason
            // (helpers.js phpInstallLanguagePacks()). Note also that the
            // snapshot sets langmenu=0 - there is no switcher inside a trial,
            // so whatever is set here is what the user gets.
            $steps[] = [
                'step' => 'installLanguagePack',
                'language' => $language,
                'setDefault' => true,
            ];
        }

        // Deliberately AFTER the language step. Found live 2026-07-23: with
        // the login first, the pack downloads and installs correctly and the
        // trial still comes up entirely in English, because Moodle serialises
        // the whole $USER into the session at login and setDefault's update to
        // user.lang then lands too late for that already-established session
        // to ever read it. Installing first makes the same blueprint render
        // Japanese - verified by booting both orderings of one blueprint.
        // Every other step below is content, so this is the only ordering
        // constraint the language step imposes.
        $steps[] = ['step' => 'login', 'username' => 'admin'];

        foreach ($allowedplugininstalls as $plugin) {
            if ($branch !== '' && self::is_baked_in($plugin['type'], $plugin['name'], $branch)) {
                // Already present and fully registered in this branch's
                // bundle (see BAKED_IN_PLUGINS docblock) — nothing to do,
                // and attempting the runtime install anyway would be
                // redundant at best and risk the exact fragile-upgrade
                // failure this exists to avoid at worst.
                continue;
            }
            // The pluginType/pluginName must be explicit: Moodle Playground only
            // auto-detects them from a GitHub-style archive URL matching
            // /<repo>/archive/... (moodle-{type}_{name} naming) - our
            // allowlist_file.php?id=N URLs never match that, so omitting
            // these silently threw "pluginType could not be detected from
            // URL" inside the sandbox on every install attempt (found live,
            // 2026-07-19, tracing why mod_quizquest never appeared in a
            // trial despite an active allowlist entry - see
            // reference-clones/moodle-playground/src/blueprint/steps/moodle-plugins.js
            // detectPluginTypeAndName()). We already know both values
            // exactly; there's no need to rely on auto-detection at all.
            $steps[] = [
                'step' => 'installMoodlePlugin',
                'url' => $plugin['zipurl'],
                'pluginType' => $plugin['type'],
                'pluginName' => $plugin['name'],
            ];
        }

        if ($resourcetype === 'activity') {
            // A single-activity backup is TYPE_1ACTIVITY, not TYPE_1COURSE —
            // the playground's own restoreCourse step handler hard-rejects
            // anything that isn't a full-course backup (verified against the
            // pinned upstream source, reference-clones/moodle-playground/src/
            // blueprint/php/helpers.js: `if ($backuptype !== backup::TYPE_1COURSE)
            // { fail(...); }`). Instead of a restoreCourse step, run a
            // self-contained runPhpCode step that creates a fresh
            // single-activity-format course and restores the activity backup
            // INTO it with TARGET_EXISTING_ADDING — modeled directly on the
            // upstream restoreCourse PHP generator's own pattern (same
            // download/extract/error-handling shape), so it behaves
            // consistently with every other blueprint step's error reporting.
            $steps[] = [
                'step' => 'runPhpCode',
                'code' => self::build_activity_restore_php($signedmbzurl),
            ];
        } else {
            $steps[] = [
                'step' => 'restoreCourse',
                'url' => $signedmbzurl,
                'category' => 'Trial',
            ];
        }

        return [
            'steps' => $steps,
            // Fresh snapshot install has only the site course (id 1) — the
            // restored course is expected to land as id 2. Verified by the
            // fidelity spike / kit smoke test; falls back gracefully to the
            // course index if wrong (restoreCourse failures are non-fatal).
            'landingPage' => '/course/view.php?id=2',
        ];
    }

    /**
     * Whether a language code is one this plugin is willing to put into a
     * blueprint: a real Moodle language code, and not English (which core
     * ships, so there is nothing to install).
     *
     * The code ends up interpolated into PHP generated inside the sandbox and
     * into a $CFG->dataroot path (reference-clones/moodle-playground/src/
     * blueprint/php/helpers.js phpInstallLanguagePacks()). The sandbox
     * validates it with this same pattern before running anything, but a
     * blueprint built here must not be the thing that carries an unvalidated
     * code to it in the first place — so anything that isn't recognisable is
     * dropped and the trial simply comes up in English.
     *
     * @param string $language
     * @return bool
     */
    private static function is_installable_language(string $language): bool {
        if ($language === '' || $language === 'en') {
            return false;
        }

        return (bool) preg_match('/^[a-z][a-z0-9_]*$/', $language);
    }

    /**
     * Build the runPhpCode step body for a single-activity Try-it: create a
     * fresh format_singleactivity course, then restore the activity backup
     * into it with TARGET_EXISTING_ADDING. See build_blueprint()'s call site
     * for why this can't reuse the restoreCourse step type.
     *
     * The leading define(CLI_SCRIPT)/require(config.php) matters: verified
     * live 2026-07-20 that — unlike the restoreCourse step — runPhpCode's
     * execution environment does NOT auto-bootstrap Moodle; its handler
     * (reference-clones/moodle-playground/src/blueprint/steps/request.js
     * handleRunPhpCode()) only prepends a bare "<?php" if missing, nothing
     * more. Without this require, raise_memory_limit() below fatals with
     * "Call to undefined function" because no config.php has ever run in
     * this PHP process. Every OTHER upstream generator in helpers.js
     * (including phpRestoreCourse(), the pattern this method is modeled on)
     * is prefixed with exactly this CLI_HEADER boilerplate for the same
     * reason — runPhpCode's own code strings are the one case that must
     * supply it manually. MOODLE_ROOT is hardcoded '/www/moodle' in
     * helpers.js too: it is the in-browser WASM mount point, fixed across
     * every trial regardless of the real Moodle site's own path, not a
     * value to derive from this plugin's $CFG.
     *
     * The generated code is kept comment-free: it is base64-encoded whole
     * into the trial's launch URL (build_launch_url()), and a verbose
     * version measurably risked tripping nginx's fastcgi response-header
     * buffer limit on the sandbox_launch.php redirect (found live
     * 2026-07-20: intermittent "upstream sent too big header", full
     * Location: URL ~5KB) — every extra byte here is a real cost.
     *
     * download_file_content() is called with the $tofile (8th) parameter
     * streaming straight to a temp path, NOT with $fullresponse=true reading
     * into a variable — verified live 2026-07-20 that the $fullresponse=true
     * form (this method's first attempt) DOES fetch successfully inside the
     * WASM sandbox, but its ->results is the response BODY BYTES, not a file
     * path; passing those bytes straight to extract_to_pathname() (which
     * expects a path and calls fopen() on it) fatals with "fopen(): Argument
     * #1 ($filename) must not contain any null bytes" the instant the binary
     * .mbz content contains one, which it does. This is the exact working
     * pattern from the upstream restoreCourse generator in helpers.js
     * (phpRestoreCourse()'s sourceBlock), reused here unchanged.
     *
     * After a successful restore, the course's format_singleactivity
     * 'activitytype' option is set to the restored module's modname —
     * verified live 2026-07-20 that without this, format_singleactivity's
     * own page_set_course() (course/format/singleactivity/lib.php) can't
     * find a course-module matching its unset/default activitytype (it
     * defaults to the first registered activity type, e.g. 'forum', not
     * whatever was actually restored) and redirects to "add an activity"
     * instead of the restored activity, even though the restore itself
     * succeeded.
     *
     * @param string $signedmbzurl
     * @return string PHP source (without the leading <?php — the runPhpCode
     *                 step handler adds it if missing)
     */
    private static function build_activity_restore_php(string $signedmbzurl): string {
        $urlliteral = str_replace("'", "\\'", $signedmbzurl);

        return <<<PHP
define('CLI_SCRIPT', true);
require('/www/moodle/config.php');
raise_memory_limit(MEMORY_EXTRA);
@set_time_limit(0);
require_once(\$CFG->dirroot . '/backup/util/includes/restore_includes.php');
require_once(\$CFG->dirroot . '/course/lib.php');
global \$CFG, \$DB, \$USER;

function fail(\$msg) {
    while (ob_get_level()) { ob_end_clean(); }
    echo json_encode(['ok' => false, 'error' => \$msg]);
    exit(0);
}
set_exception_handler(function(\$e) { fail(\$e->getMessage()); });

\$admin = get_admin();
if (!\$admin) { fail('Administrator account not found.'); }
\$USER = \$admin;

\$mbz = make_request_directory() . '/source.mbz';
\$dlok = download_file_content('$urlliteral', null, null, false, 600, 30, false, \$mbz);
if (\$dlok === false || !is_file(\$mbz) || filesize(\$mbz) < 1000) {
    fail('Could not download the activity backup.');
}

\$backupdir = restore_controller::get_tempdir_name(SITEID, \$admin->id);
\$path = make_backup_temp_directory(\$backupdir);
\$packer = get_file_packer('application/vnd.moodle.backup');
if (!\$packer->extract_to_pathname(\$mbz, \$path)) {
    fulldelete(\$path);
    fail('Could not extract the activity backup (.mbz).');
}
if (!is_file(\$path . '/moodle_backup.xml')) {
    fulldelete(\$path);
    fail('The .mbz does not contain moodle_backup.xml (not a valid Moodle backup).');
}
\$tmprc = new restore_controller(
    \$backupdir, SITEID, backup::INTERACTIVE_NO, backup::MODE_GENERAL, \$admin->id, backup::TARGET_EXISTING_ADDING
);
\$backuptype = \$tmprc->get_type();
\$tmprc->destroy();
if (\$backuptype !== backup::TYPE_1ACTIVITY) {
    fulldelete(\$path);
    fail('The supplied .mbz is not a single-activity backup.');
}

\$newcourse = new stdClass();
\$newcourse->fullname = 'Trial activity';
\$newcourse->shortname = 'trial-activity-' . time();
\$newcourse->category = 1;
\$newcourse->format = 'singleactivity';
\$course = create_course(\$newcourse);

\$rc = new restore_controller(
    \$backupdir, \$course->id, backup::INTERACTIVE_NO, backup::MODE_GENERAL, \$admin->id, backup::TARGET_EXISTING_ADDING
);
try {
    \$rc->execute_precheck();
    \$rc->execute_plan();
    \$rc->destroy();
} catch (\\Throwable \$e) {
    \$rc->destroy();
    fulldelete(\$path);
    fail('Activity restore failed: ' . \$e->getMessage());
}
fulldelete(\$path);

rebuild_course_cache(\$course->id, true);
\$modinfo = get_fast_modinfo(\$course->id);
\$restoredcm = reset(\$modinfo->get_cms());
if (\$restoredcm) {
    course_get_format(\$course)->update_course_format_options(['activitytype' => \$restoredcm->modname]);
}

echo json_encode(['ok' => true, 'courseid' => \$course->id]);
PHP;
    }

    /**
     * Build the full launch URL for a trial.
     *
     * @param string $sandboxbaseurl e.g. "https://vagrant.wisecat.net/try/"
     * @param string $branch e.g. "5.2"
     * @param array $blueprint from build_blueprint()
     * @return \moodle_url
     */
    public static function build_launch_url(string $sandboxbaseurl, string $branch, array $blueprint): \moodle_url {
        $encoded = base64_encode(json_encode($blueprint));

        return new \moodle_url(rtrim($sandboxbaseurl, '/') . '/', [
            'moodle' => $branch,
            'blueprint' => $encoded,
        ]);
    }
}
